### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by davidginn524** [ClemRz/WiFibonacci-Clock#1]
Hello
Cool project. Not really a problem more of a question. I saw that you wrote that sometimes it stops responding or gets bricked. How often does this happen? Would this be a software issue /bug?
I would like to build it but not if it freezes a lot (a lot being 1x a month)

**Comment by ClemRz** [comment]
Hi, I haven't ran it for more than a few days straight. I can't tell how likely it's going to fail (if it does). Usually the chances for it to brick increases when you have interactions with it. I.e. when you upload a file, change settings etc.
My guess is that the RAM is sometimes not enough, or the code is not optimised enough and some memory issues happen.
