### ISSUE TITLE
Colors backwards

### ISSUE THREAD

**Issue by davidginn524** [ClemRz/WiFibonacci-Clock#4]
Hello. I have finally put this together in an actual project box. It appears that the colors green and red are backwords. Red is listed as hours but it is actually minutes, Green is listed as minutes but it is actually hours. Instead of trying to debug this and figuring out where it went backwards. I changed the web interface "hours" and "minutes" section right above the pallete selection to be reversed. In addition I uploaded a new pallete color to compensate for that and it is working as expected then.  
Not expecting you to fix it. Just thought I would mention it if anyone else were to make this clock and notice is.

**Comment by davidginn524** [comment]
Nevermind I am dumb... it was  a very simple fix you chose NEO_RGB. I turned it around to NEO_GRB to fix it. clearly just a case of different ws2812b's

**Comment by ClemRz** [comment]
Hi @bizit524, I'm glad you're experiencing with that and happy to see that you found solutions to your problems! If you see room for any improvement feel free to fork and PR! :)
